/** Dialogue analysis copy for scenarios hos1–hos4 (EN + ES). Merged into i18n STRINGS. */
export const PRACTICE_ANALYSIS_STRINGS = {
  en: {
    'practice.analysis.title': 'Dialogue Analysis',
    'practice.analysis.sub': 'Key vocabulary and grammar from your response',
    'practice.analysis.yourResponse': 'Your response',
    'practice.analysis.vocab': 'Key vocabulary',
    'practice.analysis.grammar': 'Grammar focus',
    'practice.analysis.continue': 'Continue',
    'practice.analysis.back': 'Back to scenario',
    // hos1 — Renal Consultation
    'practice.hos1.a0.v1.term': 'Glomerular filtration rate (GFR)',
    'practice.hos1.a0.v1.def': 'A measure of how well the kidneys filter waste from the blood.',
    'practice.hos1.a0.v2.term': 'Labs / laboratory results',
    'practice.hos1.a0.v2.def': 'Blood tests used to track kidney function over time.',
    'practice.hos1.a0.v3.term': 'Review',
    'practice.hos1.a0.v3.def': 'To go over information carefully with the patient.',
    'practice.hos1.a0.g1.title': 'Let’s + base verb',
    'practice.hos1.a0.g1.note': 'A collaborative opener that sounds supportive, not commanding—ideal in clinical settings.',
    'practice.hos1.a0.g2.title': 'Discuss + noun phrase',
    'practice.hos1.a0.g2.note': 'Pairs an action verb with a specific medical topic to move the conversation forward clearly.',
    'practice.hos1.a1.v1.term': 'Swelling / edema',
    'practice.hos1.a1.v1.def': 'Fluid buildup, often in legs or ankles, linked to kidney issues.',
    'practice.hos1.a1.v2.term': 'Urination',
    'practice.hos1.a1.v2.def': 'The process of passing urine; changes can signal kidney problems.',
    'practice.hos1.a1.v3.term': 'Have you noticed…?',
    'practice.hos1.a1.v3.def': 'A gentle way to ask about symptoms without assuming the answer.',
    'practice.hos1.a1.g1.title': 'Present perfect + symptom question',
    'practice.hos1.a1.g1.note': '“Have you noticed…” links past changes to the present—common in intake questions.',
    'practice.hos1.a1.g2.title': 'Or — offering alternatives',
    'practice.hos1.a1.g2.note': '“Swelling… or changes in urination” lets the patient identify either symptom.',
    'practice.hos1.a2.v1.term': 'Dialysis',
    'practice.hos1.a2.v1.def': 'A treatment that filters waste from the blood when kidneys cannot.',
    'practice.hos1.a2.v2.term': 'Kidney function',
    'practice.hos1.a2.v2.def': 'How effectively the kidneys clean blood and balance fluids.',
    'practice.hos1.a2.v3.term': 'Continue to decline',
    'practice.hos1.a2.v3.def': 'To keep getting worse over time.',
    'practice.hos1.a2.g1.title': 'We may need to + verb',
    'practice.hos1.a2.g1.note': 'Softens difficult news while staying honest about possible next steps.',
    'practice.hos1.a2.g2.title': 'If + present tense, future meaning',
    'practice.hos1.a2.g2.note': '“If kidney function continues to decline” describes a real possibility without stating it as certain.',
    // hos2 — Janitorial
    'practice.hos2.a0.v1.term': 'Don PPE',
    'practice.hos2.a0.v1.def': 'To put on personal protective equipment before handling hazards.',
    'practice.hos2.a0.v2.term': 'Sanitization protocol',
    'practice.hos2.a0.v2.def': 'Step-by-step rules for cleaning and disinfecting contaminated areas.',
    'practice.hos2.a0.v3.term': 'Contact time / dwell time',
    'practice.hos2.a0.v3.def': 'How long a disinfectant must stay wet on a surface to work.',
    'practice.hos2.a0.g1.title': 'I’ll + verb (future plan)',
    'practice.hos2.a0.g1.note': 'Shows immediate action and accountability—standard in safety briefings.',
    'practice.hos2.a0.g2.title': 'First — sequencing steps',
    'practice.hos2.a0.g2.note': '“PPE first” signals correct order of operations before cleanup.',
    'practice.hos2.a1.v1.term': 'Cordon off',
    'practice.hos2.a1.v1.def': 'To block an area so others cannot enter during cleanup.',
    'practice.hos2.a1.v2.term': 'Biohazard cleanup kit',
    'practice.hos2.a1.v2.def': 'Tools and absorbents used for blood or fluid spills.',
    'practice.hos2.a1.v3.term': 'Spill',
    'practice.hos2.a1.v3.def': 'An accidental release of hazardous material onto a surface.',
    'practice.hos2.a1.g1.title': 'I’ll + two parallel actions',
    'practice.hos2.a1.g1.note': 'Linking containment and cleanup in one sentence shows a complete plan.',
    'practice.hos2.a1.g2.title': 'Area — definite reference',
    'practice.hos2.a1.g2.note': '“The area” refers to the specific spill zone the supervisor already mentioned.',
    'practice.hos2.a2.v1.term': 'Log the incident',
    'practice.hos2.a2.v1.def': 'To record the event in an official report for compliance.',
    'practice.hos2.a2.v2.term': 'Floor buffer',
    'practice.hos2.a2.v2.def': 'A machine used to polish or clean large floor surfaces.',
    'practice.hos2.a2.v3.term': 'Dwell time passes',
    'practice.hos2.a2.v3.def': 'Waiting until the required disinfectant contact time is complete.',
    'practice.hos2.a2.g1.title': 'After — time sequencing',
    'practice.hos2.a2.g1.note': '“After the dwell time passes” places mechanical cleaning in the correct order.',
    'practice.hos2.a2.g2.title': 'Run + equipment',
    'practice.hos2.a2.g2.note': '“Run the floor buffer” is natural workplace English for operating a machine.',
    // hos3 — Construction
    'practice.hos3.a0.v1.term': 'Load-bearing wall',
    'practice.hos3.a0.v1.def': 'A wall that supports weight from floors or roof above.',
    'practice.hos3.a0.v2.term': 'Engineer’s sign-off',
    'practice.hos3.a0.v2.def': 'Formal approval from a qualified engineer before work proceeds.',
    'practice.hos3.a0.v3.term': 'Sign-off',
    'practice.hos3.a0.v3.def': 'Official approval that a plan or step is safe and acceptable.',
    'practice.hos3.a0.g1.title': 'Before any + noun',
    'practice.hos3.a0.g1.note': 'Sets a non-negotiable condition before dangerous work begins.',
    'practice.hos3.a0.g2.title': 'Need — requirement, not preference',
    'practice.hos3.a0.g2.note': '“I need” communicates a professional requirement backed by code or policy.',
    'practice.hos3.a1.v1.term': 'Scaffolding tags',
    'practice.hos3.a1.v1.def': 'Labels showing inspection status and safe load limits for scaffolds.',
    'practice.hos3.a1.v2.term': 'OSHA compliance',
    'practice.hos3.a1.v2.def': 'Meeting U.S. Occupational Safety and Health Administration standards.',
    'practice.hos3.a1.v3.term': 'Inspect',
    'practice.hos3.a1.v3.def': 'To examine equipment or a site carefully for safety issues.',
    'practice.hos3.a1.g1.title': 'Let’s + verb (team proposal)',
    'practice.hos3.a1.g1.note': 'Invites the foreman into a joint safety check before work starts.',
    'practice.hos3.a1.g2.title': 'First — priority marker',
    'practice.hos3.a1.g2.note': '“First” delays the cut until compliance checks are complete.',
    'practice.hos3.a2.v1.term': 'Punch list',
    'practice.hos3.a2.v1.def': 'A list of tasks that must be finished before project closeout.',
    'practice.hos3.a2.v2.term': 'Structural review',
    'practice.hos3.a2.v2.def': 'An expert assessment of a building’s load-bearing elements.',
    'practice.hos3.a2.v3.term': 'Schedule',
    'practice.hos3.a2.v3.def': 'To arrange a time for an inspection or meeting.',
    'practice.hos3.a2.g1.title': 'Add to + list',
    'practice.hos3.a2.g1.note': 'Shows you are tracking the issue formally rather than ignoring it.',
    'practice.hos3.a2.g2.title': 'I’ll + schedule',
    'practice.hos3.a2.g2.note': 'Combines ownership (“I’ll”) with a concrete next step.',
    // hos4 — Agriculture
    'practice.hos4.a0.v1.term': 'Pesticide application',
    'practice.hos4.a0.v1.def': 'Spraying chemicals to control pests on crops.',
    'practice.hos4.a0.v2.term': 'Wind thresholds',
    'practice.hos4.a0.v2.def': 'Maximum safe wind speeds for spraying without drift.',
    'practice.hos4.a0.v3.term': 'Delay / postpone',
    'practice.hos4.a0.v3.def': 'To wait for better weather before applying chemicals.',
    'practice.hos4.a0.g1.title': 'Aren’t met — passive negative',
    'practice.hos4.a0.g1.note': 'Focuses on conditions (wind, rain) rather than blaming a person.',
    'practice.hos4.a0.g2.title': 'Should + base verb',
    'practice.hos4.a0.g2.note': 'Recommends action based on safety rules, not personal opinion alone.',
    'practice.hos4.a1.v1.term': 'Irrigation schedule',
    'practice.hos4.a1.v1.def': 'A plan for when and how much water fields receive.',
    'practice.hos4.a1.v2.term': 'Crop rotation plan',
    'practice.hos4.a1.v2.def': 'Planting different crops in sequence to protect soil health.',
    'practice.hos4.a1.v3.term': 'Adjust',
    'practice.hos4.a1.v3.def': 'To change a plan slightly to fit new conditions.',
    'practice.hos4.a1.g1.title': 'Let’s + adjust / protect',
    'practice.hos4.a1.g1.note': 'Pairs two related farm-management actions in one coordinated response.',
    'practice.hos4.a1.g2.title': 'And — linking parallel plans',
    'practice.hos4.a1.g2.note': 'Connects irrigation and rotation as parts of one weather strategy.',
    'practice.hos4.a2.v1.term': 'Harvest yield projections',
    'practice.hos4.a2.v1.def': 'Estimated crop output used to plan timing and resources.',
    'practice.hos4.a2.v2.term': 'Spray window',
    'practice.hos4.a2.v2.def': 'A short period when weather allows safe pesticide application.',
    'practice.hos4.a2.v3.term': 'Commit to',
    'practice.hos4.a2.v3.def': 'To decide firmly to go ahead with a plan.',
    'practice.hos4.a2.g1.title': 'Before we + verb',
    'practice.hos4.a2.g1.note': 'Delays the decision until data is checked—a cautious, professional tone.',
    'practice.hos4.a2.g2.title': 'Check + noun',
    'practice.hos4.a2.g2.note': '“I’ll check projections” shows data-driven field management.',
  },
  es: {
    'practice.analysis.title': 'Análisis del diálogo',
    'practice.analysis.sub': 'Vocabulario y gramática clave de tu respuesta',
    'practice.analysis.yourResponse': 'Tu respuesta',
    'practice.analysis.vocab': 'Vocabulario clave',
    'practice.analysis.grammar': 'Enfoque gramatical',
    'practice.analysis.continue': 'Continuar',
    'practice.analysis.back': 'Volver al escenario',
    'practice.hos1.a0.v1.term': 'Tasa de filtración glomerular (TFG)',
    'practice.hos1.a0.v1.def': 'Medida de qué tan bien los riñones filtran desechos de la sangre.',
    'practice.hos1.a0.v2.term': 'Análisis de laboratorio',
    'practice.hos1.a0.v2.def': 'Pruebas de sangre para seguir la función renal.',
    'practice.hos1.a0.v3.term': 'Revisar',
    'practice.hos1.a0.v3.def': 'Repasar información con cuidado junto al paciente.',
    'practice.hos1.a0.g1.title': 'Let’s + verbo base',
    'practice.hos1.a0.g1.note': 'Apertura colaborativa que suena de apoyo, no de orden.',
    'practice.hos1.a0.g2.title': 'Discuss + frase nominal',
    'practice.hos1.a0.g2.note': 'Une una acción con un tema médico específico para avanzar con claridad.',
    'practice.hos1.a1.v1.term': 'Hinchazón / edema',
    'practice.hos1.a1.v1.def': 'Acumulación de líquido, a menudo en piernas o tobillos.',
    'practice.hos1.a1.v2.term': 'Micción / orinar',
    'practice.hos1.a1.v2.def': 'Eliminar orina; los cambios pueden indicar problemas renales.',
    'practice.hos1.a1.v3.term': 'Have you noticed…?',
    'practice.hos1.a1.v3.def': 'Forma suave de preguntar síntomas sin asumir la respuesta.',
    'practice.hos1.a1.g1.title': 'Present perfect + pregunta de síntomas',
    'practice.hos1.a1.g1.note': '“Have you noticed…” vincula cambios pasados con el presente.',
    'practice.hos1.a1.g2.title': 'Or — ofrecer alternativas',
    'practice.hos1.a1.g2.note': 'Permite al paciente identificar cualquiera de los dos síntomas.',
    'practice.hos1.a2.v1.term': 'Diálisis',
    'practice.hos1.a2.v1.def': 'Tratamiento que filtra desechos cuando los riñones no pueden.',
    'practice.hos1.a2.v2.term': 'Función renal',
    'practice.hos1.a2.v2.def': 'Eficacia de los riñones para limpiar sangre y equilibrar líquidos.',
    'practice.hos1.a2.v3.term': 'Continue to decline',
    'practice.hos1.a2.v3.def': 'Seguir empeorando con el tiempo.',
    'practice.hos1.a2.g1.title': 'We may need to + verbo',
    'practice.hos1.a2.g1.note': 'Suaviza noticias difíciles manteniendo honestidad sobre próximos pasos.',
    'practice.hos1.a2.g2.title': 'If + presente, sentido futuro',
    'practice.hos1.a2.g2.note': 'Describe una posibilidad real sin afirmarla como certeza.',
    'practice.hos2.a0.v1.term': 'Don PPE / ponerse EPP',
    'practice.hos2.a0.v1.def': 'Colocarse equipo de protección personal antes de manejar riesgos.',
    'practice.hos2.a0.v2.term': 'Protocolo de sanitización',
    'practice.hos2.a0.v2.def': 'Pasos para limpiar y desinfectar áreas contaminadas.',
    'practice.hos2.a0.v3.term': 'Tiempo de contacto',
    'practice.hos2.a0.v3.def': 'Cuánto debe permanecer húmedo el desinfectante en la superficie.',
    'practice.hos2.a0.g1.title': 'I’ll + verbo (plan inmediato)',
    'practice.hos2.a0.g1.note': 'Muestra acción y responsabilidad—común en briefings de seguridad.',
    'practice.hos2.a0.g2.title': 'First — secuencia de pasos',
    'practice.hos2.a0.g2.note': '“PPE first” indica el orden correcto antes de la limpieza.',
    'practice.hos2.a1.v1.term': 'Cordon off / acordonar',
    'practice.hos2.a1.v1.def': 'Bloquear un área para que otros no entren durante la limpieza.',
    'practice.hos2.a1.v2.term': 'Kit de biohazard',
    'practice.hos2.a1.v2.def': 'Herramientas para derrames de sangre o fluidos.',
    'practice.hos2.a1.v3.term': 'Spill / derrame',
    'practice.hos2.a1.v3.def': 'Liberación accidental de material peligroso.',
    'practice.hos2.a1.g1.title': 'I’ll + dos acciones paralelas',
    'practice.hos2.a1.g1.note': 'Une contención y limpieza en un plan completo.',
    'practice.hos2.a1.g2.title': 'The area — referencia definida',
    'practice.hos2.a1.g2.note': '“The area” se refiere a la zona del derrame ya mencionada.',
    'practice.hos2.a2.v1.term': 'Log the incident / registrar',
    'practice.hos2.a2.v1.def': 'Anotar el evento en un informe oficial de cumplimiento.',
    'practice.hos2.a2.v2.term': 'Floor buffer / pulidora',
    'practice.hos2.a2.v2.def': 'Máquina para pulir o limpiar pisos grandes.',
    'practice.hos2.a2.v3.term': 'Dwell time passes',
    'practice.hos2.a2.v3.def': 'Esperar hasta que termine el tiempo de contacto del desinfectante.',
    'practice.hos2.a2.g1.title': 'After — secuencia temporal',
    'practice.hos2.a2.g1.note': 'Coloca la limpieza mecánica después del tiempo de contacto.',
    'practice.hos2.a2.g2.title': 'Run + equipo',
    'practice.hos2.a2.g2.note': '“Run the floor buffer” es inglés laboral natural para operar una máquina.',
    'practice.hos3.a0.v1.term': 'Load-bearing wall / muro de carga',
    'practice.hos3.a0.v1.def': 'Muro que soporta peso de pisos o techo superior.',
    'practice.hos3.a0.v2.term': 'Engineer’s sign-off',
    'practice.hos3.a0.v2.def': 'Aprobación formal de un ingeniero antes de proceder.',
    'practice.hos3.a0.v3.term': 'Sign-off / aprobación',
    'practice.hos3.a0.v3.def': 'Visto bueno oficial de que un plan es seguro.',
    'practice.hos3.a0.g1.title': 'Before any + sustantivo',
    'practice.hos3.a0.g1.note': 'Establece una condición obligatoria antes de trabajo peligroso.',
    'practice.hos3.a0.g2.title': 'Need — requisito profesional',
    'practice.hos3.a0.g2.note': '“I need” comunica un requisito respaldado por normas.',
    'practice.hos3.a1.v1.term': 'Scaffolding tags / etiquetas de andamio',
    'practice.hos3.a1.v1.def': 'Etiquetas de inspección y límites de carga segura.',
    'practice.hos3.a1.v2.term': 'OSHA compliance',
    'practice.hos3.a1.v2.def': 'Cumplir normas de seguridad laboral en EE. UU.',
    'practice.hos3.a1.v3.term': 'Inspect / inspeccionar',
    'practice.hos3.a1.v3.def': 'Examinar equipo o sitio en busca de riesgos.',
    'practice.hos3.a1.g1.title': 'Let’s + verbo (propuesta en equipo)',
    'practice.hos3.a1.g1.note': 'Invita al capataz a una revisión conjunta de seguridad.',
    'practice.hos3.a1.g2.title': 'First — marcador de prioridad',
    'practice.hos3.a1.g2.note': 'Retrasa el corte hasta completar las verificaciones.',
    'practice.hos3.a2.v1.term': 'Punch list / lista de pendientes',
    'practice.hos3.a2.v1.def': 'Tareas que deben completarse antes del cierre del proyecto.',
    'practice.hos3.a2.v2.term': 'Structural review',
    'practice.hos3.a2.v2.def': 'Evaluación experta de elementos estructurales.',
    'practice.hos3.a2.v3.term': 'Schedule / programar',
    'practice.hos3.a2.v3.def': 'Acordar una hora para inspección o reunión.',
    'practice.hos3.a2.g1.title': 'Add to + lista',
    'practice.hos3.a2.g1.note': 'Muestra seguimiento formal del problema.',
    'practice.hos3.a2.g2.title': 'I’ll + schedule',
    'practice.hos3.a2.g2.note': 'Combina responsabilidad con un siguiente paso concreto.',
    'practice.hos4.a0.v1.term': 'Pesticide application',
    'practice.hos4.a0.v1.def': 'Aplicación de químicos para controlar plagas en cultivos.',
    'practice.hos4.a0.v2.term': 'Wind thresholds / límites de viento',
    'practice.hos4.a0.v2.def': 'Velocidades máximas seguras para evitar deriva del producto.',
    'practice.hos4.a0.v3.term': 'Delay / posponer',
    'practice.hos4.a0.v3.def': 'Esperar mejor clima antes de fumigar.',
    'practice.hos4.a0.g1.title': 'Aren’t met — negativo pasivo',
    'practice.hos4.a0.g1.note': 'Enfoca las condiciones (viento, lluvia), no culpa a una persona.',
    'practice.hos4.a0.g2.title': 'Should + verbo base',
    'practice.hos4.a0.g2.note': 'Recomienda acción según reglas de seguridad.',
    'practice.hos4.a1.v1.term': 'Irrigation schedule',
    'practice.hos4.a1.v1.def': 'Plan de cuándo y cuánto riego reciben los campos.',
    'practice.hos4.a1.v2.term': 'Crop rotation plan',
    'practice.hos4.a1.v2.def': 'Alternar cultivos para proteger la salud del suelo.',
    'practice.hos4.a1.v3.term': 'Adjust / ajustar',
    'practice.hos4.a1.v3.def': 'Modificar un plan para nuevas condiciones.',
    'practice.hos4.a1.g1.title': 'Let’s + adjust / protect',
    'practice.hos4.a1.g1.note': 'Une dos acciones de gestión agrícola en una respuesta coordinada.',
    'practice.hos4.a1.g2.title': 'And — planes paralelos',
    'practice.hos4.a1.g2.note': 'Conecta riego y rotación como una estrategia climática.',
    'practice.hos4.a2.v1.term': 'Harvest yield projections',
    'practice.hos4.a2.v1.def': 'Estimación de producción para planificar recursos.',
    'practice.hos4.a2.v2.term': 'Spray window / ventana de fumigación',
    'practice.hos4.a2.v2.def': 'Periodo breve con clima apto para aplicar pesticidas.',
    'practice.hos4.a2.v3.term': 'Commit to / confirmar',
    'practice.hos4.a2.v3.def': 'Decidir firmemente seguir con un plan.',
    'practice.hos4.a2.g1.title': 'Before we + verbo',
    'practice.hos4.a2.g1.note': 'Retrasa la decisión hasta revisar datos.',
    'practice.hos4.a2.g2.title': 'Check + sustantivo',
    'practice.hos4.a2.g2.note': '“I’ll check projections” muestra gestión basada en datos.',
  },
} as const;
